server:
  port: 8088

spring:
  application:
    name: demo
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
        prefer-ip-address: true
      host: localhost
      port: 8500
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/
          jwk-set-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/.well-known/jwks.json
