services:
  consul:
    image: consul:1.15.4
    container_name: consul-container
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: consul agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data
    networks:
      - smr_default
    volumes:
      - consul_data:/consul/data

  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: smr
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smr_default

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-container
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - smr_default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - cluster.name=smr-elasticsearch
      - node.name=smr-node-1
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - smr_default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smr_default
    command: redis-server --appendonly yes

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana-container
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - smr_default
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  smr_default:
    driver: bridge
    name: smr_default

volumes:
  consul_data:
  mysql_data:
  elasticsearch_data:
  redis_data:
