services:
  consul:
    image: consul:1.15.4
    container_name: consul-container
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: consul agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data
    networks:
      - smr_default
    volumes:
      - consul_data:/consul/data

networks:
  smr_default:
    driver: bridge
    name: smr_default

volumes:
  consul_data:
