services:
  consul:
    image: consul:1.15.4
    container_name: consul-container
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: consul agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data
    networks:
      - smr_default
    volumes:
      - consul_data:/consul/data

  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: smr
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smr_default

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-container
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - smr_default

networks:
  smr_default:
    driver: bridge
    name: smr_default

volumes:
  consul_data:
  mysql_data:
