server:
  port: 9090
   
spring:
  profiles:
    active: cloud
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
        prefer-ip-address: true
      host: localhost
      port: 8500
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: DEMO-SERVICE
          uri: lb://demo
          predicates:
            - Path=/demo/**
          filters:
            - AddResponseHeader=X-Powered-By, SMR-CloudGateway-Service
        - id: USER-SERVICE
          uri: lb://user
          predicates:
            - Path=/auth/**
          filters:
            - AddResponseHeader=X-Powered-By, SMR-UserAuth-Service
        - id: SEARCH-SERVICE
          uri: lb://search
          predicates:
            - Path=/api/search/**
          filters:
            - AddResponseHeader=X-Powered-By, SMR-Search-Service
        - id: NOTIFICATION-SERVICE
          uri: lb://notification
          predicates:
            - Path=/notification/**
          filters:
            - AddResponseHeader=X-Powered-By, SMR-Notification-Service
        - id: LISTING-SERVICE
          uri: lb://listing
          predicates:
            - Path=/listing/**
          filters:
            - AddResponseHeader=X-Powered-By, SMR-Listing-Service
        - id: USERACTION-SERVICE
          uri: lb://user-action
          predicates:
            - Path=/actions/**
          filters:
            - AddResponseHeader=X-Powered-By, SMR-UserAction-Service


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/
          jwk-set-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/.well-known/jwks.json
      client:
        registration:
          auth0:
            client-id: Bn0vv5Qo0evMsJv44pYvEapTvHsvyYoa
            client-secret: 6bvgJT37gEt2GC68lDzpAJKfx1FUE3cJi7bkR6jowfN3jYgWZN6yJlPJHFf1NIZr
            scope:
              - openid
              - email
              - profile
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/auth0"
        provider:
          auth0:
            issuer-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/
            jwk-set-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/.well-known/jwks.json

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG

auth0:
  audience: https://dev-jr5iip1iu6v8pylo.us.auth0.com/api/v2/
