spring:
  cloud:
    consul:
      host: consul
      port: 8500
  datasource:
    url: jdbc:mysql://34.133.163.236:3306/smr
    username: root
    password: (~MHQh&2FUB(/|Hz

  # Elasticsearch Configuration
  elasticsearch:
    uris: http://34.143.174.70:9200
    username:
    password:
    connection-timeout: 10s
    socket-timeout: 60s

  # Redis Configuration for Caching
  data:
    redis:
      host: 34.143.174.70
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

  # RabbitMQ Configuration
  rabbitmq:
    host: 34.143.174.70
    port: 5672
    username: admin
    password: bInvd0fLiuQwoDj
    virtual-host: /

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/
          jwk-set-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/.well-known/jwks.json

  # Cache Configuration
  cache:
    type: redis
    cache-names:
      - propertySearch
      - trendingKeywords
      - cityAggregations
      - priceRangeAggregations
    redis:
      time-to-live: 300000 # 5 minutes

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    elasticsearch:
      enabled: true
