server:
  port: 8082

spring:
  profiles:
    active: cloud
  application:
    name: listing
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
        prefer-ip-address: true
      host: localhost
      port: 8500
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/
          jwk-set-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/.well-known/jwks.json
  datasource:
    url: jdbc:mysql://localhost:3306/smr
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    
# Logging Configuration
logging:
  level:
    com.team12.listingservice: DEBUG
    org.springframework.amqp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"